### ISSUE TITLE
Tried trendreturn=True in pandas-ta/examples/example.ipynb and got error

### ISSUE THREAD

**Issue by vijay-r** [twopirllc/pandas-ta#201]
**Describe the bug**
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'TRl'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/generic.py", line 3823, in _set_item
    loc = self._info_axis.get_loc(key)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'TRl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vkumaraguruparan/Projects/algo/SwingTrade/scrape.py", line 45, in <module>
    Chart_Helper.showChartByDur(df, ticker, 'TREND_RETURN_ERROR', interval, '1y')
  File "/Users/vkumaraguruparan/Projects/algo/SwingTrade/lib/Chart_Helper.py", line 218, in showChartByDur
    OrgChart(df,
  File "/Users/vkumaraguruparan/Projects/algo/SwingTrade/lib/Chart_Helper.py", line 1235, in __init__
    self._plot(**kwargs)
  File "/Users/vkumaraguruparan/Projects/algo/SwingTrade/lib/Chart_Helper.py", line 1392, in _plot
    self.df["TRl"] = ta.trend_return(self.df["close"], trend=long_trend, cumulative=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/frame.py", line 3163, in __setitem__
    self._set_item(key, value)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/frame.py", line 3240, in _set_item
    NDFrame._set_item(self, key, value)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/generic.py", line 3826, in _set_item
    self._mgr.insert(len(self._info_axis), key, value)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 1203, in insert
    block = make_block(values=value, ndim=self.ndim, placement=slice(loc, loc + 1))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 2711, in make_block
    return klass(values, ndim=ndim, placement=placement)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 142, in __init__
    raise ValueError(
ValueError: Wrong number of items passed 4, placement implies 1
```

**Comment by twopirllc** [comment]
Hello @vijay-r,

That is unfortunate! However you did **not** fill out the Issue Form.

Again, what version are you running? **Why did you not fill this out?**

Are you running the latest version? It is preferred.
**Installing the Latest Version**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Furthermore it appears you are not running the example notebook and instead running your ```scrape.py```.
```sh
File "/Users/vkumaraguruparan/Projects/algo/SwingTrade/scrape.py", line 45
```

The **Error** is: ```ValueError: Wrong number of items passed 4, placement implies 1```
It appears you are passing in the incorrect number of arguments.  If you would like more assistance, please kindly share reproducible code from ```scrape.py``` and hopefully I can help you resolve this Issue.

Kind Regards,
KJ

**Comment by vijay-r** [comment]
sorry my mistake. i just used `pandas-ta/examples/example.ipynb`  file and changed trendreturn=True (as highlighted below)

![image](https://user-images.githubusercontent.com/7065756/106380589-3e171b00-63ee-11eb-92f8-057954b48b15.png)

**Comment by twopirllc** [comment]
Hello @vijay-r,

**First:** upgrade to the latest version:
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Do you even have any data?

Please show me more of the prior screenshots. You practically show me nothing in order to help. There is nothing here for me to reproduce your Issue nor any way to help resolve it.

Kind Regards,
KJ
