### ISSUE TITLE
Pandas TA strategy method goes into infinite loop: Windows Freeze Support Error

### ISSUE THREAD

**Issue by mjheydari** [twopirllc/pandas-ta#235]
Hi .
my code is:

```python
import yfinance as yf
import pandas_ta as ta


sbin = yf.Ticker("SBIN.NS")
df = sbin.history(period="3d", interval="15m")
df.ta.strategy("Momentum")
```
But give warning and infinitive loop and not stop with : CTRL+C
I use Win 10 & Vscode & python 3.9.1

```sh
File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    return Popen(process_obj)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    _check_not_importing_main()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
    _check_not_importing_main()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\spawn.py", line 225, in prepare
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\spawn.py", line 105, in spawn_main
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    exitcode = _main(fd)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\spawn.py", line 114, in _main
    run_name="__mp_main__")
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 263, in run_path
    prepare(preparation_data)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\spawn.py", line 225, in prepare
    pkg_name=pkg_name, script_name=fname)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 96, in _run_module_code
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
    run_name="__mp_main__")
    exec(code, run_globals)
  File "D:\trading\0sas_algo\crash.py", line 7, in <module>
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 263, in run_path
    df.ta.strategy("Momentum")
    pkg_name=pkg_name, script_name=fname)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 96, in _run_module_code
  File "D:\trading\0sas_algo\senv\lib\site-packages\pandas_ta\core.py", line 633, in strategy
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
    pool = Pool(self.cores)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\context.py", line 119, in Pool
    exec(code, run_globals)
  File "D:\trading\0sas_algo\crash.py", line 7, in <module>
    context=self.get_context())
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\pool.py", line 176, in __init__
    df.ta.strategy("Momentum")
  File "D:\trading\0sas_algo\senv\lib\site-packages\pandas_ta\core.py", line 633, in strategy
    self._repopulate_pool()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    pool = Pool(self.cores)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\context.py", line 119, in Pool
    w.start()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\process.py", line 112, in start
    context=self.get_context())
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\pool.py", line 176, in __init__
    self._popen = self._Popen(self)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\context.py", line 322, in _Popen
    self._repopulate_pool()
    return Popen(process_obj)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\process.py", line 112, in start
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    self._popen = self._Popen(self)
    _check_not_importing_main()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\multiprocessing\context.py", line 322, in _Popen
```

**Comment by twopirllc** [comment]
Hello @mjheydari,

It is a Python multiprocessing issue and not a Pandas TA Issue. The solution has been presented various places including Issue #176 which you piggybacked on as well as the third pinned Issue #181 and of course the hints in the _original_ error message. Please take the time to read them and correct the problem. The solution is rather simple.

Furthermore, I recommend changing your DataFrame Index into a DatetimeIndex so that **vwap** will run correctly.

```python
import pandas as pd
import yfinance as yf
import pandas_ta as ta

sbin = yf.Ticker("SBIN.NS")
df = sbin.history(period="3d", interval="15m")
dtcol = # the column name for the datetime
df.set_index(pd.DatetimeIndex(df[dtcol]), inplace=True, drop=True)
df.drop(dtcol, axis=1, inplace=True)
df.ta.strategy("Momentum")
```

Please let me know if this works for you and resolves your situation.

Kind Regards,
KJ

**Comment by mjheydari** [comment]
Tanx @twopirllc  but code not work with different issue :

 ```
raise KeyError(key) from err
KeyError: 'Datetime'
``` 
and  
`dtcol = Datetime`

**Comment by mjheydari** [comment]
Did you mean:
```
import pandas as pd
import yfinance as yf
import pandas_ta as ta

sbin = yf.Ticker("SBIN.NS")
df = sbin.history(period="3d", interval="15m")
# dtcol = "Datetime"# the column name for the datetime
df.reset_index(level=0, inplace=True)
# df.set_index(pd.DatetimeIndex(df[dtcol]), inplace=True, drop=True)
df.drop(dtcol, axis=1, inplace=True)
df.ta.strategy("Momentum")
```
But not worked !

**Comment by twopirllc** [comment]
@mjheydari,

I forgot ```yfiance.Ticker()``` already returns the DataFrame with a DatetimeIndex, so no DatetimeIndex needs to be created and set.

However, give this a shot which was explained in the above Issues #176 and #181 as well as the error message. 

```python
import yfinance as yf
import pandas_ta as ta

if __name__ == "__main__":
    sbin = yf.Ticker("SBIN.NS")
    df = sbin.history(period="3d", interval="15m")
    df.ta.strategy("Momentum")
```

Since you are likely not making an executable, you do not need ```freeze_support()``` in the ```__main__``` block.

![Screen Shot 2021-02-27 at 8 26 28 AM](https://user-images.githubusercontent.com/18198392/109393314-c8f81200-78d5-11eb-8116-d6d74e281776.png)

Let me know if it works

KJ

**Comment by twopirllc** [comment]
Hello @mjheydari,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ

**Comment by mjheydari** [comment]
yes work correctly. I force install Linux to use library but not ideal for all user .

**Comment by twopirllc** [comment]
@mjheydari,

> yes work correctly in pervious condition win10 and vscode and py 3.9

Great! I'm glad it is working now as intended.

> I force install Linux to use library but not ideal for all user .

What does this mean?

KJ

**Comment by mjheydari** [comment]
TNX @twopirllc 
must be use  `if __name__ == "__main__":` for solve issue without this  in (win10 and vscode) doesn't work.

**Comment by twopirllc** [comment]
@mjheydari,

Yeah, that's a Python Windows Issue. There is only so much I can do there. Others seem to be working with ```if __name__ == "__main__"``` on Windows just fine. No one is forcing you to install Linux to get this to work.

KJ
