### ISSUE TITLE
getting valueerror when using strategy all

### ISSUE THREAD

**Issue by copypasteearth** [twopirllc/pandas-ta#244]
Im using the github version with pip

**Describe the bug**
I am just getting a value error when trying to get strategyall()

```sh
Traceback (most recent call last):
  File "C:\Users\copyp\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\copyp\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "C:\Users\copyp\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas_ta\core.py", line 429, in _mp_worker
    return getattr(self, method)(*args, **kwargs)
  File "C:\Users\copyp\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas_ta\core.py", line 750, in ebsw
    result = ebsw(close=close, length=length, bars=bars, offset=offset, **kwargs)
  File "C:\Users\copyp\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas_ta\cycles\ebsw.py", line 55, in ebsw
    ebsw = Series(result, index=close.index)
  File "C:\Users\copyp\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\series.py", line 348, in __init__
    raise ValueError(
ValueError: Length of passed values is 40, index implies 35.
```

The above exception was the direct cause of the following exception:

```sh
Traceback (most recent call last):
  File "profile.py", line 675, in <module>
    dat,ind,ret = get_data(tick,period)
  File "profile.py", line 33, in get_data
    df.ta.strategy()
  File "C:\Users\copyp\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas_ta\core.py", line 704, in strategy
    [self._post_process(r, **kwargs) for r in results]
  File "C:\Users\copyp\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas_ta\core.py", line 704, in <listcomp>
    [self._post_process(r, **kwargs) for r in results]
  File "C:\Users\copyp\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 448, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "C:\Users\copyp\AppData\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 868, in next
    raise value
ValueError: Length of passed values is 40, index implies 35.
```

<br/>

```python
def get_data(ticker,period):
    """
    Gets data from CSV (0 - AAPL, 1 - MSI, 2 - SBUX).
    :return: T x 3 Stock Prices
    """
    ticker = yf.Ticker(ticker)
    df = ticker.history(period=period,interval='1d')

    #df = df.dropna()

    df.ta.strategy()
    return df
```

i will provide more info if you need it, thanks for your time

**Comment by copypasteearth** [comment]
another update, the ticker PLTK is actually a recent IPO so there may just not be enough data

**Comment by copypasteearth** [comment]
yeah, there is actually only 35 days worth of data for that stock, it would be great if you could put in like a fillna(0) or something like that for stocks like that

**Comment by twopirllc** [comment]
Hello @copypasteearth,

Yes. Looks like this case now needs to be covered. If you want it done _soon_, it would be great if you could fork, edit the ```strategy``` method in ```core.py``` to account for this case and submit a PR. 😎 

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @copypasteearth,

I have a _Development Version_ version available that hopefully addresses this. Simply run:
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

If you want to go back to the **Latest Version**. Version: *0.2.48b* Run:
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

This is similar to Issue #125. Please let me know what your think when you get a chance.

Thanks,
KJ
