### ISSUE TITLE
stoch and stochrsi not working

### ISSUE THREAD

**Issue by ReubenHawley** [twopirllc/pandas-ta#322]
python 3.9
0.2.97b0

**Describe the bug**

```sh
Traceback (most recent call last):
  File "C:\Users\equal\AppData\Roaming\JetBrains\PyCharm2021.1\scratches\scratch_2.py", line 15, in <module>
    df["fastk"] = ta.stoch(high=df["high"], low=df["low"], close=df["close"], smooth_k=14)
  File "C:\Users\equal\PycharmProjects\event_que\venv\lib\site-packages\pandas\core\frame.py", line 3163, in __setitem__
    self._set_item(key, value)
  File "C:\Users\equal\PycharmProjects\event_que\venv\lib\site-packages\pandas\core\frame.py", line 3243, in _set_item
    NDFrame._set_item(self, key, value)
  File "C:\Users\equal\PycharmProjects\event_que\venv\lib\site-packages\pandas\core\generic.py", line 3829, in _set_item
    self._mgr.insert(len(self._info_axis), key, value)
  File "C:\Users\equal\PycharmProjects\event_que\venv\lib\site-packages\pandas\core\internals\managers.py", line 1203, in insert
    block = make_block(values=value, ndim=self.ndim, placement=slice(loc, loc + 1))
  File "C:\Users\equal\PycharmProjects\event_que\venv\lib\site-packages\pandas\core\internals\blocks.py", line 2751, in make_block
    return klass(values, ndim=ndim, placement=placement)
  File "C:\Users\equal\PycharmProjects\event_que\venv\lib\site-packages\pandas\core\internals\blocks.py", line 142, in __init__
    raise ValueError(
ValueError: Wrong number of items passed 2, placement implies 1
```

**To Reproduce**

```python
import ccxt
import pandas as pd
import pandas_ta as ta
exchange = ccxt.binance()

bars = exchange.fetch_ohlcv('BTC/USDT', timeframe='1m', limit=100)
df = pd.DataFrame(bars[:-1], columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
df.set_index(pd.DatetimeIndex(df["timestamp"]), inplace=True)
df.ta.cores = 16

df["fastk"] = ta.stoch(high=df["high"], low=df["low"], close=df["close"], smooth_k=14)
print(df)
```

**Expected behavior**
i would expect to see a dataframe with pandas data series of the stoch

**Comment by twopirllc** [comment]
Hello @ReubenHawley,

This is **not** a bug. Both ```ta.stoch``` and ```ta.stochrsi``` return a DataFrame, not a Series.
See ```help(ta.stoch)``` and ```help(ta.stochrsi)``` where _returns_ are listed at the bottom of the help.

Additionally, ```df.ta.cores = 16``` only works when using ```df.ta.strategy()```. See [Multiprocessing)](https://github.com/twopirllc/pandas-ta#multiprocessing) on the README.

Working code:
```python
import ccxt
import pandas as pd
import pandas_ta as ta
from datetime import datetime

exchange = ccxt.binance()

to_dt = lambda x: datetime.utcfromtimestamp(float(x) / 1000.0)

bars = exchange.fetch_ohlcv('BTC/USDT', timeframe='1m', limit=100)

df = pd.DataFrame(bars, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
ts = df["timestamp"].apply(to_dt)
df.set_index(pd.DatetimeIndex(ts), inplace=True)
df.drop(columns=["timestamp"], inplace=True)
df.ta.cores = 16
df.ta.stoch(smooth_k=14, append=True)
print(df)
```

Hope this helps! Let me know if this works for you.

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @ReubenHawley,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ

**Comment by ReubenHawley** [comment]
thank you very much, apologies for the late response, well done on creating this library. excellent work.

**Comment by twopirllc** [comment]
@ReubenHawley,

No worries. Thanks for getting back to me regardless. I appreciate it.

Thank you,
KJ
