### ISSUE TITLE
ARRTIBUTEERROR : “none type” object has no attribute “ta”

### ISSUE THREAD

**Issue by Ylelmon** [twopirllc/pandas-ta#377]
How can I fix it ?

**Comment by twopirllc** [comment]
@Ylelmon,

You **need** to provide more information than that. Preferably the code that causes that. Including Pandas TA version as previously requested. Imports used et al.

Kind Regards,

**Comment by Ylelmon** [comment]
import get_data as gd
import pandas as pd
import pandas_ta as ta
import mplfinance as mpf
import time
import numpy as np

ticker = "XLMUSDT"
interval = "15m"
depth = "720 hours ago UTC+1"

df = gd.get_klines(ticker, interval, depth)
df_analyse = pd.DataFrame()

data = df.ta.wma(close = df["Close"], length=20)
df["wma_20"] = data
df["signals_buy"] = np.nan
df["signals_sell"] = np.nan

buy = 0
for i in df.index:
    close = df["Close"][i]
    low = df["Low"][i]
    high = df["High"][i]
    wma_20 = df["wma_20"][i]
    if close < wma_20 and buy == 0:
        df["signals_buy"][i] = low
        buy = 1
    if close > wma_20 and buy == 1:
        df["signals_sell"][i] = high
        buy = 0

signals_buy = mpf.make_addplot(df['signals_buy'],type='scatter', markersize=60, marker='^', color = "g")
signals_sell = mpf.make_addplot(df['signals_sell'],type='scatter', markersize=60, marker='v', color = "r")
wma_20 = mpf.make_addplot(df["wma_20"])
mpf.plot(df,type='candle', volume=True, style='binance', addplot=[wma_20, signals_buy, signals_sell])
 
That is the cod but still the same problem

**Comment by twopirllc** [comment]
@Ylelmon,

Please post the stack trace.

Thanks,
KJ

**Comment by Ylelmon** [comment]
Traceback (most recent call last):
  File "c:/Users/DELL/Desktop/bot/indicator.py", line 28, in <module>
    data=df.ta.vwap(high=df['High'], low=df['Low'], close=df['Close'], volume= df['Volume'], anchor=None, offset=None, )
AttributeError: 'NoneType' object has no attribute 'ta'

**Comment by Ylelmon** [comment]
Traceback (most recent call last):
  File "c:/Users/DELL/Desktop/bot/indicator.py", line 28, in <module>
    data=df.ta.vwap(high=df['High'], low=df['Low'], close=df['Close'], volume= df['Volume'], anchor=None, offset=None, )
AttributeError: 'NoneType' object has no attribute 'ta'

**Comment by twopirllc** [comment]
@Ylelmon,

Your traceback does not match your code. You are not even using ```df.ta.vwap()``` in the code you originally provided.

However, ```ARRTIBUTEERROR : “none type” object has no attribute “ta”``` means that your Pandas DataFrame is of type ```None``` meaning you have **no** data in the DataFrame and Pandas TA can not access it's data (rows & columns) to process ```df.ta.wma()```. Make sure you have data first before applying ```ta```.

```python
import get_data as gd
import pandas as pd
import pandas_ta as ta
import mplfinance as mpf
import time
import numpy as np

ticker = "XLMUSDT"
interval = "15m"
depth = "720 hours ago UTC+1"

df = gd.get_klines(ticker, interval, depth)

# What is the output of this?
print(f"df[{type}:{df.shape}\n{df}")
```

Also ```get_data``` is no module that I know of nor can I find via [PyPi](https://pypi.org/search/?q=get_data), so I can't replicate your line ```df = gd.get_klines(ticker, interval, depth)```.

Kind Regards,
KJ

**Comment by twopirllc** [comment]
@Ylelmon,

So have you ran the code I posted above with the last ```print(f"df[{type}:{df.shape}\n{df}")``` that I requested? What are it's values?

KJ

**Comment by Ylelmon** [comment]
Yes the value is <class "type">(96,10)
By the way gd is another file in my folder

**Comment by twopirllc** [comment]
@Ylelmon,

If the shape is (96,10), then where is the rest of the DataFrame print out?

It is rather _difficult_ to assist you when you do not provide enough details or purposefully omit them.

**Comment by Ylelmon** [comment]
Sorry but I'm not purposefully omit them. And that all data I got do want to see the code ?

**Comment by Ylelmon** [comment]
client = Client(api_key=Pkey, api_secret=Skey) 
tickers ='BTCUSDT'
interval=Client.KLINE_INTERVAL_5MINUTE
depth = "8 Hours ago UTC+3"
for ticker in tickers :
    def pulldate(tickers , interval , depth):
            Cdate = client.get_historical_klines(tickers, interval, depth)
            print (Cdate)
            df =pd.DataFrame(Cdate)
            print(df)
            if not df.empty :
            #Cleandate
            #Convert timestamp to readable datetime
                df[0]=pd.to_datetime(df[0],unit='ms')


            #Change column name from numbrs
                df.columns = ['Date','Open','High','Low','Close','Volume','IGNORE','Quote_Volume','Trades_Count','BUY_VOL','BUY_VOL_VAL','x']
                df = df.set_index('Date')


            #Delete unecessary column
                del df['IGNORE']    
                del df ['BUY_VOL']
                del df ['BUY_VOL_VAL']
                del df['x']
            
            
            #Convert to numbers
                df ["Open"] = pd.to_numeric(df["Open"])
                df ["High"] = pd.to_numeric(df["High"])
                df ["Low"] = pd.to_numeric(df["Low"])
                df ["Close"] = pd.to_numeric(df["Close"])
                df ["Volume"] = round(pd.to_numeric(df["Volume"]))
                df ["Quote_Volume"] = round(pd.to_numeric(df["Quote_Volume"]))
                df ["Trades_Count"] = pd.to_numeric(df["Trades_Count"])
            

                #Add new column
               
                df['div']= df['Open'] / df['Close']	
                df['Log_VolumeGain'] = (np.log(df["Quote_Volume"]/df.Quote_Volume.shift(1))*100).fillna(0)
                df['pricegain'] = (df.Open.pct_change()*100).fillna(0)
                Low_price = min(df['Low'])
                High_price = max(df['High'])    
                pricegain = round(High_price * 100)/ Low_price *2
                


                print("-----------------",tickers,"-----------")
                print('Low_price : ', str(Low_price))
                print('High_price : ' , str(High_price),)
                print('pricegain :',str(pricegain), '%')
                print('-----------------------------------------')

            return(df)

**Comment by Ylelmon** [comment]
this is new code and the value df[<class 'pandas.core.frame.DataFrame'>:(96, 10)

**Comment by twopirllc** [comment]
@Ylelmon,

I am unable to access binance for some reason today. Can you please upload a sample csv of one of the tickers with the necessary columns?

Thanks,
KJ

**Comment by Ylelmon** [comment]
Okay no I can't because if do that the value will be none type” object has no attribute “ta”

**Comment by twopirllc** [comment]
@Ylelmon,

> this is new code and the value df[<class 'pandas.core.frame.DataFrame'>:(96, 10)

Apparently you were able to.

And you can save the the data to csv like so:
```python
import pandas as pd
import pandas_ta as ta
# your other imports

client = Client(api_key=Pkey, api_secret=Skey) 
tickers ='BTCUSDT'
interval=Client.KLINE_INTERVAL_5MINUTE
depth = "8 Hours ago UTC+3"

Cdate = client.get_historical_klines(tickers, interval, depth)
print (Cdate)
df =pd.DataFrame(Cdate)

# Writes the csv, then upload here
pd.to_csv("BTCUSDT.csv")
```

Thanks,
KJ

**Comment by Ylelmon** [comment]
Oh god think u

**Comment by Ylelmon** [comment]
[BTCUSDT.csv](https://github.com/twopirllc/pandas-ta/files/7042319/BTCUSDT.csv)
