### ISSUE TITLE
error on getting ADX values.

### ISSUE THREAD

**Issue by GoldenGeese** [twopirllc/pandas-ta#445]
I wanted to create a new column for my pd data frame which has the adx values. I followed exactly what arguments does the indicator need like this:

```python
new_d['ADX_15'] = ta.adx(high=new_d['high'],low=new_d['low'],close=new_d['close'],length=15)
```

but it gave me an error when I ran it:
```sh

Traceback (most recent call last):
  File "C:\Users\marit\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'ADX_15'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\marit\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\frame.py", line 3751, in _set_item_mgr
    loc = self._info_axis.get_loc(key)
  File "C:\Users\marit\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'ADX_15'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\marit\PycharmProjects\BOH_Black_box\USDT_Pairs.py", line 94, in <module>
    new_d['ADX_15'] = ta.adx(high=new_d['high'],low=new_d['close'],close=new_d['close'],length=15)
  File "C:\Users\marit\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\frame.py", line 3602, in __setitem__
    self._set_item_frame_value(key, value)
  File "C:\Users\marit\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\frame.py", line 3742, in _set_item_frame_value
    self._set_item_mgr(key, arraylike)
  File "C:\Users\marit\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\frame.py", line 3754, in _set_item_mgr
    self._mgr.insert(len(self._info_axis), key, value)
  File "C:\Users\marit\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\internals\managers.py", line 1162, in insert
    block = new_block(values=value, ndim=self.ndim, placement=slice(loc, loc + 1))
  File "C:\Users\marit\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\internals\blocks.py", line 1937, in new_block
    check_ndim(values, placement, ndim)
  File "C:\Users\marit\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\internals\blocks.py", line 1979, in check_ndim
    raise ValueError(
ValueError: Wrong number of items passed 3, placement implies 1
```

I tried using lambdas and apply() function like this:
```python
new_d['ADX_7'] = new_d.apply(lambda row: ta.adx(row['high'],row['low'],row['close'], length=7),axis=1)
```
However, it gave me None values in that column

**Comment by twopirllc** [comment]
Hello @GoldenGeese,

Indicators return either a Series (1 column) or a DataFrame (2 or more columns). To easily figure out which it returns use ```help(ta.<indicator name>)``` and look at the bottom for the expected columns. For **adx** in particular, it returns a DataFrame with columns: **adx**, **dmp**, **dmn** columns.

So in your code:

```python
new_d['ADX_15'] = ta.adx(high=new_d['high'],low=new_d['close'],close=new_d['close'],length=15)
```
you are trying to stuff a multicolumn DataFrame into a single column DataFrame (_ValueError: Wrong number of items passed 3, placement implies 1_), which Pandas does not like nor know how to resolve.

If you want just **adx** and manually add it to ```new_d``` yourself, you can do:
```python
new_d['ADX_15'] = ta.adx(high=new_d['high'],low=new_d['close'],close=new_d['close'], length=15).iloc[:,0]
```

_Note_: You might not get what you expect with ```low=new_d['close']``` argument, unless that was your intention. 🤷🏼‍♂️ 

<br/>

Also, there is no need for this...
```python
new_d['ADX_7'] = new_d.apply(lambda row: ta.adx(row['high'],row['low'],row['close'], length=7),axis=1)
```
Pandas TA does this with the use of the [DataFrame Extension Convention](https://github.com/twopirllc/pandas-ta#programming-conventions) to easily apply the results to the existing DataFrame.

```python
new_d.ta.adx(length=7, append=True)  # Appends all 3 columns of adx to new_d
```
If you don't need the other two columns, **dmp** and **dmn**, just drop them afterwards.

<br/>

Hope this helps!

Kind Regards,
KJ

**Comment by twopirllc** [comment]
Hello @GoldenGeese,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ

**Comment by Chigstardan** [comment]
Thanks so much! I was agonizing over this issue for over 3 hours! Thanks for explaining.
