### ISSUE TITLE
JMA indicator ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by zhemaituk** [twopirllc/pandas-ta#454]
pandas-ta: 0.3.14b0

Running `df.ta.strategy()` or more specifically `df.ta.jma()` on a simple dataframe fails with

```sh
Error
Traceback (most recent call last):
  File "/Users/andrei/Projects/BE/breakingequity/breakingequity-backtest-single-day/tests/test_ohlcdata.py", line 60, in test_jma
    df.ta.jma()
  File "/Users/andrei/.local/share/virtualenvs/breakingequity-backtest-single-day-Vn0CDZ8S/lib/python3.9/site-packages/pandas_ta/core.py", line 1199, in jma
    result = jma(close=close, length=length, phase=phase, offset=offset, **kwargs)
  File "/Users/andrei/.local/share/virtualenvs/breakingequity-backtest-single-day-Vn0CDZ8S/lib/python3.9/site-packages/pandas_ta/overlap/jma.py", line 76, in jma
    jma[0:_length - 1] = npNaN
ValueError: cannot convert float NaN to integer
```

Sample unit test:
```python
    def test_jma(self):
        minutes_range = pd.date_range(
            start=pd.Timestamp('2020-01-02 09:30:00-05:00'),
            end=pd.Timestamp('2020-01-02 16:00:00-05:00'),
            freq='1min')
        minutes = 390

        ohlc = [
            [1, 2, 1, 2, 10, 1.5],
            [2, 4, 2, 4, 20, 3.0],
            [3, 4, 3, 4, 20, 3.0],
        ]
        df = pd.DataFrame(
            ohlc * int(minutes / len(ohlc)),
            columns=['open', 'high', 'low', 'close', 'volume', 'vwap'],
            index=minutes_range[0:minutes]
        )

        df.ta.jma()
```

**Comment by twopirllc** [comment]
Hello @zhemaituk,

So luckily it was a quick and easy fix. It is now available on the _development_ branch if you want to verify it and let me know.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks,
KJ

**Comment by zhemaituk** [comment]
Works like a charm, thank you!
