### ISSUE TITLE
Issue Calculating "doji" without enough candles. 

### ISSUE THREAD

**Issue by MerlinR** [twopirllc/pandas-ta#492]
**Issue**

**Versions**:
Python: 3.9.10
pandas_ta: 0.3.14b0 (git install)
TA-Lib: 0.4.24
ta-lib-config: 

**Error Message**
```sh
2022-02-17 14:12:31,968 | ERROR | base_events:asyncio:default_exception_handler:1738  | Exception in callback TaskWrapper.on_task_done(<Task finishe...bute 'name'")>)
handle: <Handle TaskWrapper.on_task_done(<Task finishe...bute 'name'")>)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/libraries/cm_utils/cm_utils/utils/async_utils.py", line 27, in on_task_done
    fut.result()
  File "/libraries/cm_brokers/cm_brokers/backtester/source.py", line 200, in _stream_ticker
    await callback(tick)
  File "/app/service.py", line 104, in process_ticker_updates
    await self.create_indicators(ticker_update.id)
  File "/app/service.py", line 128, in create_indicators
    self.markets[market].candles.ta.cdl_pattern(name=["dojistar", "doji"], append=True)
  File "/usr/local/lib/python3.9/site-packages/pandas_ta/core.py", line 874, in cdl_pattern
    result = cdl_pattern(open_=open_, high=high, low=low, close=close, name=name, offset=offset, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pandas_ta/candles/cdl_pattern.py", line 57, in cdl_pattern
    result[pattern_result.name] = pattern_result
AttributeError: 'NoneType' object has no attribute 'name'
```

**Describe the bug**
When attempting to calculate the "Doji" indicator i get that error message. This does NOT happen when calling "dojistar" it appears to be an issue when calling the following:
```python
# Patterns that implemented in pandas-ta
    pta_patterns = {
        "doji": cdl_doji, "inside": cdl_inside,
    }
```
I get the same error when calling strategy.all, however not tracked that down any further then this, or confirmed same issue, however very likely. I am building up the dataseries as i get live data, and therefore my series starts with 1 candle row as I add more, however each time i add a row i re-calculate the indicators.

**Tracked down**
So i wanted to avoid creating an error as the issue, so after I stepped through my code during the doji creation at:
```sh
57: result[pattern_result.name] = pattern_result
```
I found that the _candles/cdl_doji.py_ will return None if the length is considered to short less than (10) as each value (open,high..) is passed to _verify_series_ which will overwrite each one with None if less then the length.
```
if open_ is None or high is None or low is None or close is None:
        return
```
This in turn makes _pattern_result_ a None value and of course None has no attributes.

**To Reproduce**
```python
import pandas_ta as ta
import pandas as pd

dict_data = {
    "open": {
        pd.Timestamp("2021-11-03 14:00:00", freq="10S"): 15982.7,
        pd.Timestamp("2021-11-03 14:00:10", freq="10S"): 15984.2,
        pd.Timestamp("2021-11-03 14:00:20", freq="10S"): 15984.0,
    },
    "high": {
        pd.Timestamp("2021-11-03 14:00:00", freq="10S"): 15986.4,
        pd.Timestamp("2021-11-03 14:00:10", freq="10S"): 15986.0,
        pd.Timestamp("2021-11-03 14:00:20", freq="10S"): 15985.5,
    },
    "low": {
        pd.Timestamp("2021-11-03 14:00:00", freq="10S"): 15982.2,
        pd.Timestamp("2021-11-03 14:00:10", freq="10S"): 15982.1,
        pd.Timestamp("2021-11-03 14:00:20", freq="10S"): 15977.2,
    },
    "close": {
        pd.Timestamp("2021-11-03 14:00:00", freq="10S"): 15984.5,
        pd.Timestamp("2021-11-03 14:00:10", freq="10S"): 15983.2,
        pd.Timestamp("2021-11-03 14:00:20", freq="10S"): 15977.2,
    },
    "volume": {
        pd.Timestamp("2021-11-03 14:00:00", freq="10S"): 323,
        pd.Timestamp("2021-11-03 14:00:10", freq="10S"): 210,
        pd.Timestamp("2021-11-03 14:00:20", freq="10S"): 433,
    },
}

new = {
    "open": {
        pd.Timestamp("2021-11-03 14:00:30", freq="10S"): 15966.1,
    },
    "high": {
        pd.Timestamp("2021-11-03 14:00:30", freq="10S"): 15967.5,
    },
    "low": {
        pd.Timestamp("2021-11-03 14:00:30", freq="10S"): 15966.1,
    },
    "close": {
        pd.Timestamp("2021-11-03 14:00:30", freq="10S"): 15966.5,
    },
    "volume": {
        pd.Timestamp("2021-11-03 14:00:30", freq="10S"): 29,
    },
}


def candle_compress_dataframe(data: pd.DataFrame, frame: str = "10S"):
    """
    Frame is timeframe, Hours(H), Minutes(T), Seconds(S):
    E.G 1T = 1 min | 10S = 10 seconds
    """
    ohlc_dict = {
        "open": "first",
        "high": "max",
        "low": "min",
        "close": "last",
        "volume": "sum",
    }

    for col in data.columns:
        if col not in ohlc_dict.keys():
            ohlc_dict[col] = "last"

    data = data.resample(frame, closed="left", label="left").apply(ohlc_dict)
    return data


df = pd.DataFrame.from_dict(dict_data)

df = pd.concat([df, pd.DataFrame.from_dict(new)], sort=False)
df = candle_compress_dataframe(df)
df.ta.cdl_pattern(name=["dojistar", "doji"], append=True)

print(df)
```

**Expected behavior**
Doji indicator is added as 0

**Additional context**
I spent a good day googling and debug this unsure the issue, could find no references to this error. I ended up stepping through to find the cause. So glad i did.

**Comment by MerlinR** [comment]
Thanks for the reply! This makes sense, I get the change not wanting to create invalid data if length is too low.
Im not suggesting removing the length check.
```
    if open_ is None or high is None or low is None or close is None:
        return
```
However if the  function _cdl_doji_ called at _pta_patterns[n]_ (in below snippet) can return **None**, then the function _cdl_pattern_ shouldn't attempt to access an attribute it, which causes the exception.
```
if n in pta_patterns:
            pattern_result = pta_patterns[n](
                open_, high, low, close, offset=offset, scalar=scalar, **kwargs
            )
            result[pattern_result.name] = pattern_result
```

A possible solution to stopping people running into this exception without causing indicators is to simply check the return type prior to attempting to access the attribute:
```
if n in pta_patterns:
            pattern_result = pta_patterns[n](
                open_, high, low, close, offset=offset, scalar=scalar, **kwargs
            )
            if not isinstance(pattern_result,Series):
                continue          
            result[pattern_result.name] = pattern_result
```

Thanks for replying so quick!

**Comment by twopirllc** [comment]
Hello @MerlinR,

Some updates to _development_ branch this past month should handle and DataFrame size of at least 1 row now.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

If you could give it a test and let me know what you think, that would be great!

Thanks,
KJ

**Comment by MerlinR** [comment]
Hey @twopirllc 
Appoligies for LONG delay, can confirm this appears to be resolved.
Thanks for the hard work!
