### ISSUE TITLE
issue with macd

### ISSUE THREAD

**Issue by hanging-man** [twopirllc/pandas-ta#557]
i have a code which looks like this 

```python
        d1['RSI'] = d1.ta.rsi().fillna(0).round(2)
        d1['SMA20'] = d1.ta.sma(length=20).fillna(0).round(2)
        d1['SMA50'] = d1.ta.sma(length=50).fillna(0).round(2)

        d1['MACD'] = d1.ta.macd().MACD_12_26_9.round(2)
        d1['MACDH'] = d1.ta.macd().MACDh_12_26_9.round(2)
        d1['MACDS'] = d1.ta.macd().MACDs_12_26_9.round(2)
```

since last 4 days I am getting an error with MACD calculation 

I am copy pasting the error message below. 

I have very basic knowledge of python, so any help on how to circumvent this issue would be of great help.
Thanks. 

```sh
I:\PycharmProjects\pythonProject\fno_indicators.py:58: FutureWarning: reindexing with a non-unique Index is deprecated and will raise in a future version.
  d1['MACD'] = d1.ta.macd().MACD_12_26_9.round(2)
Traceback (most recent call last):
  File "I:\PycharmProjects\pythonProject\fno_indicators.py", line 58, in <module>
    d1['MACD'] = d1.ta.macd().MACD_12_26_9.round(2)
  File "H:\fin\lib\site-packages\pandas_ta\core.py", line 1013, in macd
    result = macd(close=close, fast=fast, slow=slow, signal=signal, offset=offset, **kwargs)
  File "H:\fin\lib\site-packages\pandas_ta\momentum\macd.py", line 67, in macd
    df = DataFrame(data)
  File "H:\fin\lib\site-packages\pandas\core\frame.py", line 636, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "H:\fin\lib\site-packages\pandas\core\internals\construction.py", line 502, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "H:\fin\lib\site-packages\pandas\core\internals\construction.py", line 125, in arrays_to_mgr
    arrays = _homogenize(arrays, index, dtype)
  File "H:\fin\lib\site-packages\pandas\core\internals\construction.py", line 607, in _homogenize
    val = val.reindex(index, copy=False)
  File "H:\fin\lib\site-packages\pandas\core\series.py", line 4672, in reindex
    return super().reindex(**kwargs)
  File "H:\fin\lib\site-packages\pandas\core\generic.py", line 4966, in reindex
    return self._reindex_axes(
  File "H:\fin\lib\site-packages\pandas\core\generic.py", line 4986, in _reindex_axes
    obj = obj._reindex_with_indexers(
  File "H:\fin\lib\site-packages\pandas\core\generic.py", line 5032, in _reindex_with_indexers
    new_data = new_data.reindex_indexer(
  File "H:\fin\lib\site-packages\pandas\core\internals\managers.py", line 679, in reindex_indexer
    self.axes[axis]._validate_can_reindex(indexer)
  File "H:\fin\lib\site-packages\pandas\core\indexes\base.py", line 4107, in _validate_can_reindex
    raise ValueError("cannot reindex on an axis with duplicate labels")
ValueError: cannot reindex on an axis with duplicate labels
```

**Comment by twopirllc** [comment]
Hello @hanging-man,

Which version of Pandas TA are you running? Do you have TA Lib installed? Has it been working before the previous 4 days? Do you have more code that you are leaving out to share so someone can replicate the Error? Since this is a Pandas Error and not a Pandas TA Error, have you searched [here](https://www.google.com/search?q=ValueError%3A+cannot+reindex+on+an+axis+with+duplicate+labels) for help on resolving it?

Kind Regards,
KJ

**Comment by hanging-man** [comment]
I would like to thank you for pointing out that this is a pandas error and not a pandas ta error. I couldn't have figured that out. However after that I tried to do some research as to where problem was and figured out that data from two dates in may had duplicate values. After I rectifed it the code ran. 
Please pardon me for asking such a silly question. I have very basic programming skills. 
Thanks again.
Anirban

**Comment by twopirllc** [comment]
@hanging-man,

> I would like to thank you for pointing out that this is a pandas error and not a pandas ta error. I couldn't have figured that out. ... Please pardon me for asking such a silly question. I have very basic programming skills.

No worries. Glad you were able to figure it out and resolve the duplicated values. 😎 

As a new programmer, I understand there is a lot to digest and it can be overwhelming when you see a wall text in a Stack Trace. The good news is, you are not likely to be the only one to receive such an error and many of them have possible solutions already via a search. Keep programming and you will get better. 😎

Kind Regards,
KJ
