### ISSUE TITLE
Probable type error in ADX indicator evaluation

### ISSUE THREAD

**Issue by duoduoffff** [twopirllc/pandas-ta#569]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```
`0.3.14b0`

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```
Yes, installed

**Did you upgrade? Did the upgrade resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Yes, upgraded

**Describe the bug**

Here's the dataframe I am using to evaluate the ADX indicator:

```dataframe
                time   close    code        date forexName    high     low    open     max     min  close_di
0     1159200000000  7.9173  USDCNY  2006-09-26    美元兑人民币  7.9210  7.9146  7.9210  7.9210  7.9146  7.917550
1     1159286400000  7.9046  USDCNY  2006-09-27    美元兑人民币  7.9105  7.9043  7.9105  7.9105  7.9043  7.906000
2     1159372800000  7.9046  USDCNY  2006-09-28    美元兑人民币  7.9055  7.8979  7.9046  7.9055  7.8979  7.903150
3     1159459200000  7.9086  USDCNY  2006-09-29    美元兑人民币  7.9087  7.9021  7.9024  7.9087  7.9021  7.907000
4     1159718400000  7.9073  USDCNY  2006-10-02    美元兑人民币  7.9073  7.9073  7.9073  7.9073  7.9073  7.907300
...             ...     ...     ...         ...       ...     ...     ...     ...     ...     ...       ...
3995  1657209600000  6.6950  USDCNY  2022-07-08    美元兑人民币  6.7077  6.6900  6.6948  6.7077  6.6900  6.696925
3996  1657468800000  6.7180  USDCNY  2022-07-11    美元兑人民币  6.7195  6.6962  6.6962  6.7195  6.6962  6.712925
3997  1657555200000  6.7248  USDCNY  2022-07-12    美元兑人民币  6.7375  6.7179  6.7363  6.7375  6.7179  6.726250
3998  1657641600000  6.7187  USDCNY  2022-07-13    美元兑人民币  6.7382  6.7161  6.7265  6.7382  6.7161  6.722925
3999  1657728000000  6.7547  USDCNY  2022-07-14    美元兑人民币  6.7686  6.7225  6.7281  6.7686  6.7225  6.750125

[4000 rows x 11 columns]
```

When I run the following:

```python3
ta.adx(high=foundationDF.high, low=foundationDF.low, close=foundationDF.close)["ADX_{0}".format(length)]
```

I am getting:

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 163, in _na_arithmetic_op
    result = func(left, right)
  File "/home/user/.local/lib/python3.9/site-packages/pandas/core/computation/expressions.py", line 239, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
  File "/home/user/.local/lib/python3.9/site-packages/pandas/core/computation/expressions.py", line 69, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for -: 'str' and 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/user/git/projectRoot/CI/Business/ForeignExcg/evaluateDmi.py", line 61, in <module>
    file.FileOperations.writeToFile(json.dumps(retIntersections("USDCNY", resultLimit=32)), "./out_dmi_neo.json")
  File "/mnt/c/Users/user/git/projectRoot/CI/Business/ForeignExcg/evaluateDmi.py", line 56, in retIntersections
    t = applyDmi(t)
  File "/mnt/c/Users/user/git/projectRoot/CI/Business/ForeignExcg/evaluateDmi.py", line 26, in applyDmi
    jsonObj = evalDmi.CI.getAdxFromTALib(jsonObj)
  File "../../../Businesses/Generic/evaluateDmi.py", line 47, in getAdxFromTALib
    foundationDF["ADX"] = ta.adx(high=foundationDF.high, low=foundationDF.low, close=foundationDF.close)["ADX_{0}".format(length)]
  File "/home/user/.local/lib/python3.9/site-packages/pandas_ta/trend/adx.py", line 26, in adx
    up = high - high.shift(drift)  # high.diff(drift)
  File "/home/user/.local/lib/python3.9/site-packages/pandas/core/ops/common.py", line 70, in new_method
    return method(self, other)
  File "/home/user/.local/lib/python3.9/site-packages/pandas/core/arraylike.py", line 108, in __sub__
    return self._arith_method(other, operator.sub)
  File "/home/user/.local/lib/python3.9/site-packages/pandas/core/series.py", line 5639, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
  File "/home/user/.local/lib/python3.9/site-packages/pandas/core/base.py", line 1295, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "/home/user/.local/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 222, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)
  File "/home/user/.local/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 170, in _na_arithmetic_op
    result = _masked_arith_op(left, right, op)
  File "/home/user/.local/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 108, in _masked_arith_op
    result[mask] = op(xrav[mask], yrav[mask])
TypeError: unsupported operand type(s) for -: 'str' and 'str'
```

Seems that the library is having a type problem, but I looked at the source code, in your `adx.py` code, in line 26, it reads `up = high - high.shift(drift)`, meaning that it should be a pandas series minus another pandas series, it couldn't be a "string", anyway.

**To Reproduce**
Provide sample code.

**Expected behavior**

**Screenshots**

**Additional context**
Using Debian WSL inside Windows 10 x64 enterprise edition.

Thanks for using Pandas TA!

**Comment by twopirllc** [comment]
Hello @duoduoffff,

I see that you closed the Issue without any additional information. So were you able to resolve the issue?

Have you tried the _development_ version?
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Kind Regards,
KJ

**Comment by duoduoffff** [comment]
Yes, I have looked at my data again and realized that what I had passed into the library were exactly strings, instead of evaluatable numbers. It shouldn't be the library's fault.

**Comment by twopirllc** [comment]
@duoduoffff,

Doh! Yeah, that could drive Pandas to return that error. Glad you were able to find your mistake. 😎 

KJ
