### ISSUE TITLE
'Series' object has no attribute 'append' in v0.3.14b

### ISSUE THREAD

**Issue by DenizBerkP** [twopirllc/pandas-ta#739]
`print(ta.version)`
0.3.14b0

**Have you tried the _development_ version? Did it resolve the issue?**

I tried but not working.

`data.ta.strategy(exclude=["supertrend", "qqe", "psar", "hilo"])`

```sh
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas_ta\core.py", line 467, in _mp_worker
    return getattr(self, method)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas_ta\core.py", line 1225, in mcgd
    result = mcgd(close=close, length=length, offset=offset, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas_ta\overlap\mcgd.py", line 24, in mcgd
    mcg_ds = close[:1].append(mcg_cell[1:])
             ^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\core\generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Series' object has no attribute 'append'

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
Cell In[4], line 29
     26 for hisse in bist_hisseleri:  
     27     data = yf.download(hisse + ".IS", start=startDate,end=endDate, interval="1d")
---> 29     data.ta.strategy(exclude=["supertrend", "qqe", "psar", "hilo"])
     30     data = data.dropna(axis='columns', subset=[data.index[-1]], how='all')
     32     data[f"{hisse} Günlük Değişim"] = ((data['Close'] - data['Open']) / data['Open']) * 100 

File C:\ProgramData\anaconda3\Lib\site-packages\pandas_ta\core.py:792, in AnalysisIndicators.strategy(self, *args, **kwargs)
    789         self._last_run = get_time(self.exchange, to_string=True)
    791 # Apply prefixes/suffixes and appends indicator results to the  DataFrame
--> 792 [self._post_process(r, **kwargs) for r in results]
    794 if verbose:
    795     print(f"[i] Total indicators: {len(ta)}")

File C:\ProgramData\anaconda3\Lib\site-packages\pandas_ta\core.py:792, in <listcomp>(.0)
    789         self._last_run = get_time(self.exchange, to_string=True)
    791 # Apply prefixes/suffixes and appends indicator results to the  DataFrame
--> 792 [self._post_process(r, **kwargs) for r in results]
    794 if verbose:
    795     print(f"[i] Total indicators: {len(ta)}")

File C:\ProgramData\anaconda3\Lib\site-packages\tqdm\std.py:1178, in tqdm.__iter__(self)
   1175 time = self._time
   1177 try:
-> 1178     for obj in iterable:
   1179         yield obj
   1180         # Update and possibly print the progressbar.
   1181         # Note: does not call self.update(1) for speed optimisation.

File C:\ProgramData\anaconda3\Lib\multiprocessing\pool.py:423, in <genexpr>(.0)
    415 result = IMapIterator(self)
    416 self._taskqueue.put(
    417     (
    418         self._guarded_task_generation(result._job,
   (...)
    421         result._set_length
    422     ))
--> 423 return (item for chunk in result for item in chunk)

File C:\ProgramData\anaconda3\Lib\multiprocessing\pool.py:873, in IMapIterator.next(self, timeout)
    871 if success:
    872     return value
--> 873 raise value

AttributeError: 'Series' object has no attribute 'append'
```

**Comment by raychan0410** [comment]
same problem here. I had to change 'All' to 'common' to get rid of the error, so error should be caused by some 'non-common' strategies

**Comment by twopirllc** [comment]
Hello @DenizBerkP & @raychan0410,

Have you tried this with the _development_ branch? If not, that's where we should start. It has not only indicator speed improvements but 

#### Installation
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```
[Docs](https://github.com/twopirllc/pandas-ta/tree/development)

Also, I suggest setting ```cores=0``` to see if it improves _ta_ performance. [Multiprocessing](https://github.com/twopirllc/pandas-ta#multiprocessing) is _not_ always quicker. It has management overhead for running its multiprocessing pool.

In your ```for``` loop:
```python
#  v0.3.14b
data.ta.cores = 0
data.ta.strategy(exclude=["supertrend", "qqe", "psar", "hilo"])```

# development
#  - also ta.strategy renamed to ta.study
data.ta.study(exclude=["supertrend", "qqe", "psar", "hilo"], cores=0) 
```

Let me know if that helps.

Kind Regards
KJ
For more _development_ examples, see the [Study Notebook](https://github.com/twopirllc/pandas-ta/blob/development/examples/PandasTA_Study_Examples.ipynb)

**Comment by raychan0410** [comment]
yay it worked perfectly!
Thanks for help @twopirllc . Appreciated.

**Comment by gaomeng1900** [comment]
The problem seems to be "mcgd". It worked after I added "mcgd" to exclude.

**Comment by Se6T** [comment]
I have had the same error. 
The problem was in line 25: 
`mcg_ds = close[:1].append(mcg_cell[1:])`

replacing _append_ with _pd.concat_ solved it:

`mcg_ds = pd.concat([close[:1], mcg_cell[1:]])`
