### ISSUE TITLE
df.ta.Strategy('All') - Error, due to deprecated append method on Pandas, need to update to use pandas.concat method.

### ISSUE THREAD

**Issue by calebfowowe** [twopirllc/pandas-ta#809]
There is a bug which make it relatively impossible to use the All strategy method in the Library. 

it relates to the fact that the append method has been deprecated on the most recent versions of Pandas. Hence, I get an error every time I try to use the functionality. Apparently, everywhere in this code where Dataframe results have been appended to a series, needs to be updated to use the pandas.concat method instead. 

Do you think you can help fix this and release an updated version of this library. This is a really useful library.

I have made attempt to try and fix this from my end, but hasn't been successful so far. 

See example of the bug: The AttributeError: 'Series' object has no attribute 'append':

```sh
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/calebfowowe/Documents/Files - Caleb/CQF/January 2024/Classes - January 2024/Python_Labs/MachineLearning/pythonProject/.venv/lib/python3.10/site-packages/pandas_ta/core.py", line 467, in _mp_worker
    return getattr(self, method)(*args, **kwargs)
  File "/Users/calebfowowe/Documents/Files - Caleb/CQF/January 2024/Classes - January 2024/Python_Labs/MachineLearning/pythonProject/.venv/lib/python3.10/site-packages/pandas_ta/core.py", line 1225, in mcgd
    result = mcgd(close=close, length=length, offset=offset, **kwargs)
  File "/Users/calebfowowe/Documents/Files - Caleb/CQF/January 2024/Classes - January 2024/Python_Labs/MachineLearning/pythonProject/.venv/lib/python3.10/site-packages/pandas_ta/overlap/mcgd.py", line 24, in mcgd
    mcg_ds = close[:1].append(mcg_cell[1:])
  File "/Users/calebfowowe/Documents/Files - Caleb/CQF/January 2024/Classes - January 2024/Python_Labs/MachineLearning/pythonProject/.venv/lib/python3.10/site-packages/pandas/core/generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'append'
"""

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
Cell In[40], line 1
----> 1 df.ta.strategy("All")

File ~/Documents/Files - Caleb/CQF/January 2024/Classes - January 2024/Python_Labs/MachineLearning/pythonProject/.venv/lib/python3.10/site-packages/pandas_ta/core.py:792, in AnalysisIndicators.strategy(self, *args, **kwargs)
    789         self._last_run = get_time(self.exchange, to_string=True)
    791 # Apply prefixes/suffixes and appends indicator results to the  DataFrame
--> 792 [self._post_process(r, **kwargs) for r in results]
    794 if verbose:
    795     print(f"[i] Total indicators: {len(ta)}")

blah blah blah ...
```

**Comment by twopirllc** [comment]
Hello @calebfowowe,

Thanks for nuking the Bug Report template and overriding what was asked. This is a duplicate issue and has been fixed on the _development_ branch. If it doesn't fix the issue, please open a new Issue and fill out the Bug Report template appropriately.

Kind Regards,
KJ
