### ISSUE TITLE
Getting error TypeError: unsupported operand type(s) for /: 'str' and 'float' while using vwap from pandas_ta

### ISSUE THREAD

**Issue by prashantrpatil** [twopirllc/pandas-ta#816]
I am using following versions
numpy 2.0.1
pandas 2.2.2
pandas_ta 0.3.14b0
python 3.11.14

For calculating vwap i am trying  code 
**oneMinDF1['vwap'] = ta.vwap(oneMinDF1.inth, oneMinDF1.intl, oneMinDF1.intc, oneMinDF1.v)**

but getting exception **TypeError: unsupported operand type(s) for /: 'str' and 'float'** 

Exception trace:
Traceback (most recent call last):
  File "C:\Users\Prashant Patil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\ops\array_ops.py", line 218, in _na_arithmetic_op
    result = func(left, right)
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\Prashant Patil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\computation\expressions.py", line 242, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prashant Patil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\computation\expressions.py", line 73, in _evaluate_standard
    return op(a, b)
           ^^^^^^^^
TypeError: unsupported operand type(s) for /: 'str' and 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Prashant Patil\Downloads\ShoonyaApi-py-master (1)\ShoonyaApi-py-master\tests\test_tvwap_PRP", line 79, in <module>
    oneMinDF1['vwap'] = ta.vwap(oneMinDF1.inth, oneMinDF1.intl, oneMinDF1.intc, oneMinDF1.v)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prashant Patil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas_ta\overlap\vwap.py", line 15, in vwap
    typical_price = hlc3(high=high, low=low, close=close)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prashant Patil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas_ta\overlap\hlc3.py", line 20, in hlc3
    hlc3 = (high + low + close) / 3.0
           ~~~~~~~~~~~~~~~~~~~^~~~~~~
  File "C:\Users\Prashant Patil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\ops\common.py", line 76, in new_method
    return method(self, other)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prashant Patil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\arraylike.py", line 210, in __truediv__
    return self._arith_method(other, operator.truediv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prashant Patil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\series.py", line 6135, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prashant Patil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\base.py", line 1382, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prashant Patil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\ops\array_ops.py", line 283, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)  # type: ignore[arg-type]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Prashant Patil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\ops\array_ops.py", line 227, in _na_arithmetic_op
    result = _masked_arith_op(left, right, op)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  **File "C:\Users\Prashant Patil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\ops\array_ops.py", line 182, in _masked_arith_op
    result[mask] = op(xrav[mask], y)
                   ^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for /: 'str' and 'float'**

**Comment by prashantrpatil** [comment]
Following is data in dataframe oneMinDF1

                       into    inth    intl    intc         v
date
2024-07-24 09:54:00  250.30  280.20  223.20  244.15  38072475
2024-07-24 09:53:00  132.30  271.75  129.40  247.10  36678435
2024-07-24 09:52:00  111.85  133.30  111.85  131.40  33937470
2024-07-24 09:51:00  116.00  121.55  111.60  112.25  33512325
2024-07-24 09:50:00  109.70  122.00  109.50  117.75  33269835
2024-07-24 09:49:00  122.85  122.85  107.55  111.75  32890485
2024-07-24 09:48:00  122.95  123.85  111.95  121.05  32431020

**Comment by prashantrpatil** [comment]
Data inside the dataframe has to be typecasted then it worked.

**Comment by twopirllc** [comment]
Hello @prashantrpatil 

Glad you were able to resolve the issue yourself. To keep Pandas TA slim and fast, it does not do pre/post processing and has basic assumptions. Some data sources are seamless and others need that pre-processing.

Furthermore, I recommend using the _development_ version for better compatibility with python 3.11 and Pandas 2.x. However you may need to downgrade numpy as 2.x is not fully supported yet by several downstream dependents. As numpy 2.x becomes more prevalent, it too will be supported.

Kind Regards,
KJ
