### ISSUE TITLE
Add python 3.13 support

### ISSUE THREAD

**Issue by a-Rahmati** [twopirllc/pandas-ta#863]
I tried to install the development version on my Python 3.13 but I get this error:

```
$ sudo pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
Collecting git+https://github.com/twopirllc/pandas-ta.git@development
  Cloning https://github.com/twopirllc/pandas-ta.git (to revision development) to /tmp/pip-req-build-fmvbxe1l
  Running command git clone --filter=blob:none --quiet https://github.com/twopirllc/pandas-ta.git /tmp/pip-req-build-fmvbxe1l
  Running command git checkout -b development --track origin/development
  Switched to a new branch 'development'
  branch 'development' set up to track 'origin/development'.
  Resolved https://github.com/twopirllc/pandas-ta.git to commit 438f3a97b71b26bc17efb1a204fb0e0fdc48e0aa
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numba>=0.59.0 (from pandas_ta==0.4.19b0)
  Downloading numba-0.60.0.tar.gz (2.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 884.2 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/usr/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-_8llvsio/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-_8llvsio/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-_8llvsio/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-_8llvsio/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 51, in <module>
        File "<string>", line 48, in _guard_py_ver
      RuntimeError: Cannot install on Python version 3.13.0; only versions >=3.9,<3.13 are supported.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Please add support for this version of python.

Thanks

**Comment by twopirllc** [comment]
Hello @a-Rahmati 

If you want 3.13 support. You will need to contribute at this point.

Fork, check out the _development_ branch, make edits and submit a PR.

Kind Regards,
KJ

**Comment by XotEmBotZ** [comment]
3.13 is not possible now as numba is not updated to support python3.13

**Comment by twopirllc** [comment]
Please see #901
